### PR TITLE
Adding support for DNSSD

### PR DESCRIPTION
**Pull request by thehellmaker**
This is for adding support for DNSSD Library along with NSDService on android. DNSSD is faster and more reliable and its advantages has been mentioned in the issue https://github.com/balthazar/react-native-zeroconf/issues/77

### CODE REVIEW

**Comment by balthazar** [comment]
Ah you managed to open the PR :smile:

**Comment by thehellmaker** [comment]
> Ah you managed to open the PR 😄

Yeah finally. It was stupid :P But hey I hadn't opened a PR on an open repo before. So there's always a first time

**Comment by meriadec** [comment]
When can we have this merged? I need it for my project

**Comment by thehellmaker** [comment]
@meriadec I'm waiting for comments from @balthazar.  Post that i can accelerate changes if any and merge

**Comment by thehellmaker** [comment]
@balthazar Just wanted to followup. Any updates on the review ?

**Comment by balthazar** [comment]
I'm not sure about your comment about not knowing iOS. You don't really need to have expertise in that since the only thing you're touching is the Android part. Couldn't we pass an extra object param that contains the implementation to use for Android?

**Comment by thehellmaker** [comment]
Added a parameter called implementation which defaults to old implementation type and thus wherever customer wants they can choose the new DNSSD implementation

**Comment by thehellmaker** [comment]
Added fixes for crash handling and converting exceptions to Error event

**Comment by balthazar** [comment]
Will merge that considering the tests that have been done for it by @haykodarb

**Comment by balthazar** [comment]
Published as of `0.13.0`

**Comment by haykodarb** [comment]
I found a bug that appeared only when generating the .apk

"RNZeroconf.stop() got 0 arguments, expected 1"

Trying to see where .stop() is being called from and why it throws an error when not passed any arguments.

Shouldn't "Platform" be included from "react-native"  in index.js?

**Comment by balthazar** [comment]
How was it working without it exactly? Publishing patch.

**Comment by haykodarb** [comment]
Tried the fix and it isn't it, unfortunately. 

I'm not sure how it worked without including Platform but it's currently working when debugging through USB but not when installing the apk manually.

I'll keep debugging.

Should I comment here if I find a solution? What's the proper form?

**Comment by haykodarb** [comment]
It was an issue with how I was generating the .apk file, not with the library.

My bad, sorry for not trying harder before commenting.

**Comment by meriadec** [comment]
Works fine on my side! Amazing :rocket:

**Comment by tunm1228** [comment]
> Published as of `0.13.0`

please publish version

**Comment by balthazar** [comment]
@tunm1228 it is published what are you talking about 🤡

**Comment by tunm1228** [comment]
> @tunm1228 it is published what are you talking about 🤡

Hey I am wondering how we can lookup for a particular host. I tried having multiple hosts but it shows only one I looked through all the issues but couldn't find anything.

**Comment by balthazar** [comment]
Don't spam unrelated threads.

**Pull request merged**
